DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    CITY VARCHAR(255),
    BLDG_NUMBER VARCHAR(255),
    STREET_NAME VARCHAR(255),

    INDEX IDX_PERSON_ID (ID)
);