CREATE DATABASE DEMO;

DROP TABLE IF EXISTS DEMO.PERSON;

CREATE TABLE DEMO.PERSON
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    CITY VARCHAR(255),
    BLDG_NUMBER VARCHAR(255),
    STREET_NAME VARCHAR(255),

    INDEX IDX_PERSON_ID (ID)
);